### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wongsyrone** [wongsyrone/lede-1#1]
- [x] UKSM(https://github.com/dolohow/uksm/blob/master/uksm-4.6.patch) drop irrelevant changes
- [x] iptables dependency issue https://github.com/openembedded/openembedded-core/tree/master/meta/recipes-extended/iptables/iptables
- [x] wr2041nv1: disable ar9344 flow ctrl
- [x] add pdnsd
- [x] LOW PRIO - try to add fping
- [x] pdnsd merge changes from https://github.com/fmbiete/pdnsd
- [x] curl
- [x] enlarge git clone depth
- [x] uksm the latest patch, drop trailing spaces
- [x] cleanup Build/Prepare rules https://github.com/lede-project/source/commit/7c8c3226dc8ecd2b77d1d1e8215e0fbb52819cd7
- [x] backport random changes to linux 4.4, it seems we have to stay on LTS kernel for a long time
- [x] use new pppd source, alpine linux musl header fixes
- [x] change wr2041n-v1 squashfs block size to 512;  add opkg
- [x] mwlwifi, import fs-libev update, compile new version

**Comment by wongsyrone** [comment]
ss
```sh
#!/bin/sh /etc/rc.common
# Copyright (C) 2016 wongsyrone

. /lib/functions.sh

START=95
USE_PROCD=1
#PROCD_DEBUG=1

CONF=/etc/shadowsocks.json

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/ss-redir -c $CONF -b 0.0.0.0 -t 600 -u
	procd_set_param file $CONF
	procd_set_param user root # run service as user root
	procd_set_param stdout 1 # forward stdout of the command to logd
	procd_set_param stderr 1 # same for stderr
	procd_close_instance
	procd_open_instance
	procd_set_param command /usr/bin/ss-tunnel -c $CONF -b 0.0.0.0 -t 20 -l 5353 -L 8.8.8.8:53 -u
	procd_set_param file $CONF
	procd_set_param user root # run service as user root
	procd_set_param stdout 1 # forward stdout of the command to logd
	procd_set_param stderr 1 # same for stderr
	procd_close_instance
}

reload_service() {
	stop
	sleep 5s
	start
}

```

**Comment by wongsyrone** [comment]
vlmcsd
```sh
#!/bin/sh /etc/rc.common
# Copyright (C) 2016 wongsyrone

. /lib/functions.sh

START=95
USE_PROCD=1
#PROCD_DEBUG=1

PROG=/usr/sbin/vlmcsd
INIFILE=/etc/vlmcsd.ini
LISTENPORT=1688
ENABLED='0'

config_load "vlmcsd"

parse_vlmcsd()
{
	config_get LISTENPORT "$section" "port"
	config_get ENABLED "$section" "enabled"
}
config_foreach parse_vlmcsd 'vlmcsd'

start_service() {
	if [ "1" = "$ENABLED" ] || [ "on" = "$ENABLED" ] || [ "true" = "$ENABLED" ]; then
		procd_open_instance
		procd_set_param command $PROG -D -d -i $INIFILE -P $LISTENPORT -l syslog -r 2
		procd_set_param file $CONF
		procd_set_param user root # run service as user root
		procd_set_param stdout 1 # forward stdout of the command to logd
		procd_set_param stderr 1 # same for stderr
		procd_close_instance
	else
		echo "vlmcsd is disabled!"
	fi
}

reload_service() {
	stop
	sleep 2s
	start
}

```

**Comment by wongsyrone** [comment]
- [x] revert https://github.com/lede-project/source/commit/e64463ebde554071431514925825e2c30f2b6998

**Comment by vertesmark** [comment]
My "wish":
diff -Nau0r a/comment b/comment
--- a/comment	2017-10-15 12:31:41.942554874 +0200
+++ b/comment	2017-10-15 12:32:29.373218646 +0200
@@ -5 +5 @@
-LOW PRIO - try to add fping
+MEDIUM PRIO - try to add fping

...now I just copied my old OpenWrt /usr/bin/fping to current LEDE.
Dirty, but works.

**Comment by wongsyrone** [comment]
- [x] pptp revert
- [x] add v2ray readv
- [x] enable ccache
- [x] rework iremap
- [x] ppp static link to openssl crypto library

**Comment by wongsyrone** [comment]
- [x] cleanup packages feeds and external packages
- [ ] drop unmaintained in-tree package
- [x] pcap-dnsproxy

**Comment by wongsyrone** [comment]
- [x] add ip6tables mods corresponding to iptables
- [x] split built-in packages into a separate package
